Fixing escaping of strings, added more expressive use of references operator

diff --git a/install b/install
--- a/install
+++ b/install
@@ -15,6 +15,11 @@ if [ $? != 2 ]; then
 fi
 
 re2c -o scanner.c scanner.re && ./lemon -s parser.lemon && cat base.c >> parser.c
+if [ ! -f parser.c ]; then
+  echo "error: re2c is not installed"
+  exit 2
+fi
+
 sed s/"\#line"/"\/\/"/g scanner.c > xx && mv -f xx scanner.c
 sed s/"#line"/"\/\/"/g parser.c > xx && mv -f xx parser.c
 export CFLAGS="-g3 -O0"
